apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: "rc1a-iareqhnrq8smtcrj.mdb.yandexcloud.net"
        - name: PMA_PORT
          value: "3306"
        - name: PMA_USER
          value: "netology_user"
        - name: PMA_PASSWORD
          value: "hN76dIILRL7WhSzD"
        - name: UPLOAD_LIMIT
          value: "100M"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-lb
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP